# Source
# https://github.com/iced-rs/iced/blob/master/.github/workflows/build.yml

name: Build
on:
  push:
    branches:
      - gui
    tags:
      - '*'


jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: hecrj/setup-rust-action@v1
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - uses: actions/checkout@master
      - name: Build cracker_gui binary
        run: cargo build --verbose --profile release-opt --package cracker_gui
      - name: Rename
        run: mv target/release-opt/cracker_gui bedrock_cracker-x86_64-unknown-linux-gnu
      - name: Archive cracker_gui binary
        uses: actions/upload-artifact@v3
        with:
          name: bedrock_cracker-x86_64-unknown-linux-gnu
          path: bedrock_cracker-x86_64-unknown-linux-gnu

  create_release:
    needs: [linux]
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          tag_name: test
          path: artifacts-dl
      - name: Move files from sub folders into one folder
        run: |
          mkdir artifacts
          find artifacts-dl/ -type f -exec mv -t artifacts/ {} +
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
